# Generated by Django 4.0.1 on 2022-01-08 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0002_alter_database_ssh_private_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='database',
            name='ssh_method',
            field=models.CharField(choices=[('password', 'Password'), ('private_key', 'Private key')], default='password', max_length=255),
        ),
    ]
