# Generated by Django 4.0.1 on 2022-01-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0003_alter_database_ssh_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='pagination',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='query',
            name='per_page',
            field=models.IntegerField(default=50),
        ),
    ]
