# Generated by Django 4.0.1 on 2022-01-10 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0004_query_pagination_query_per_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='order_by',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
