# Generated by Django 4.0.1 on 2022-01-10 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0005_query_order_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='per_page',
            new_name='page_size',
        ),
    ]
