# Generated by Django 4.0.1 on 2022-01-10 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0006_rename_per_page_query_page_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='param',
            name='default',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
