# Generated by Django 4.0.1 on 2022-01-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queries', '0007_param_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='query',
            field=models.TextField(blank=True, null=True),
        ),
    ]
